spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true

management:
  endpoint:
    shutdown:
      enabled: true
  server:
    servlet:
      context-path: /api
    add-application-context-header: false

application:
  name: ${project.name}
  version: ${project.version}
  url: ${project.url}
  commit: ${git.commit.id.abbrev}
  timestamp: ${maven.build.timestamp}