server:
  address: 127.0.0.1
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lightning?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  data:
    elasticsearch:
      properties:
        home: ./
security:
  user:
    name: admin
    password: password

lightning:
  host: https://moekr.com
  eof: ''
  copyright: ''
  analytics:
    app-name: lightning
    app-id: UA-12345678-1
    view-id: 12345678
    begin-date: 2018-01-01
    key-file: key.json