server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlite:D:/blog/sqlite.db
  jpa:
    database-platform: com.moekr.blog.data.dialect.SQLite3Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
  thymeleaf:
    cache: false
security:
  user:
    name: admin
    password: admin
endpoints:
  shutdown:
    enabled: true
management:
  context-path: /api
  add-application-context-header: false
